jobs:
  build:
    environment: release
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: setup repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: setup node.js
        uses: actions/setup-node@v2
        with:
          cache: 'npm'
          node-version: '18'
      - run: npm ci
      - run: npm run build
    timeout-minutes: 10
  lint:
    environment: release
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: setup repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: setup node.js
        uses: actions/setup-node@v2
        with:
          cache: 'npm'
          node-version: '18'
      - run: npm ci
      - run: npm run lint
    timeout-minutes: 10
  test:
    env:
      TEST_ONLY_NON_INTEGRATION: 'true'
    environment: release
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: setup repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: setup node.js
        uses: actions/setup-node@v2
        with:
          cache: 'npm'
          node-version: '18'
      - run: npm ci
      - run: npm run test
    timeout-minutes: 10
  test-pg-integration:
    env:
      TEST_ONLY_PG_INTEGRATION: 'true'
    environment: release
    name: Test "pg" integration
    runs-on: ubuntu-latest
    services:
      postgres:
        env:
          POSTGRES_DB: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
        image: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - name: setup repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: setup node.js
        uses: actions/setup-node@v2
        with:
          cache: 'npm'
          node-version: '18'
      - run: npm ci
      - env:
          POSTGRES_DSN: postgres:postgres@localhost:5432
        run: npm run test
    timeout-minutes: 10
  test-postgres-integration:
    env:
      TEST_ONLY_POSTGRES_INTEGRATION: 'true'
    environment: release
    name: Test "postgres" integration
    runs-on: ubuntu-latest
    services:
      postgres:
        env:
          POSTGRES_DB: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
        image: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - name: setup repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: setup node.js
        uses: actions/setup-node@v2
        with:
          cache: 'npm'
          node-version: '18'
      - run: npm ci
      - env:
          POSTGRES_DSN: postgres:postgres@localhost:5432
        run: npm run test
    timeout-minutes: 10
name: Test and build
on:
  push:
  pull_request:
